apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: suwetha-gateway
  namespace: suwetha-ns
spec:
  gatewayClassName: gateway
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same
